# Generated by Django 2.1.3 on 2019-02-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
