# Generated by Django 2.1.3 on 2019-01-31 08:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20181213_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='active_key',
            field=models.CharField(blank=True, max_length=128, verbose_name='код подтверждения'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 8, 1, 14, 637515, tzinfo=utc)),
        ),
    ]
