# Generated by Django 2.1.3 on 2019-02-27 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_auto_20190227_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 9, 13, 21, 580752, tzinfo=utc)),
        ),
    ]
