# Generated by Django 2.1.3 on 2019-02-27 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_auto_20190227_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 9, 29, 13, 830672, tzinfo=utc)),
        ),
    ]
